---
- block:
    - name: pkg | dnf-plugins-core
      dnf: name=dnf-plugins-core state=latest

    - name: pkg | python3 builddeps
      command: dnf builddep -y python3
      register: dnf_output
      changed_when: '"Installing:" in dnf_output.stdout'
  become: true
  become_user: root
  tags: system
